name: Test Android build
on:
  pull_request:
    paths:
      - .github/workflows/build-android.yml
      - android/**
      - cpp/**
      - example/package.json
      - example/android/**
      - react-native.config.js
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-android.yml
      - android/**
      - cpp/**
      - example/package.json
      - example/android/**
      - react-native.config.js

jobs:
  build:
    if: github.repository == 'Expensify/react-native-live-markdown'
    runs-on: ubuntu-latest
    concurrency:
      group: build-android-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        # v4
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Java 17
        # v4
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install node_modules
        run: npm ci

      - name: Build app
        working-directory: example/android
        run: ./gradlew assembleDebug --build-cache -PreactNativeArchitectures=arm64-v8a
