name: Test Android build
on:
  pull_request:
    paths:
      - .github/workflows/build-android.yml
      - android/**
      - example/package.json
      - example/android/**
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-android.yml
      - android/**
      - example/package.json
      - example/android/**

jobs:
  build:
    if: github.repository == 'Expensify/react-native-live-markdown'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [example]
      fail-fast: false
    concurrency:
      group: android-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build app
        working-directory: ${{ matrix.working-directory }}/android
        run: ./gradlew assembleDebug --build-cache -PreactNativeArchitectures=arm64-v8a
